name: Build, Test, Package and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: github.event_name != 'pull_request' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ Release ]

    outputs:
      release_version: ${{ steps.get_release_info.outputs.release_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'e2ca0145eda96cb8b2f972d9ff4b7bd1619fefa0'
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgInstall: false

      - name: Set up CMake, Ninja, and required tools
        shell: pwsh
        run: |
          if ("${{ runner.os }}" -eq "Linux") {
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build
          } elseif ("${{ runner.os }}" -eq "Windows") {
            choco install -y cmake ninja nsis
          } else {
            return 1
          }

      - name: Build, Test and Package
        shell: pwsh
        run: |
          Invoke-Expression ("
            ./scripts/build_test_and_package.ps1
              -OS ${{ runner.os }}
              -BuildType ${{ matrix.build_type }} 
              -VCPKG_ROOT ${{ github.workspace }}/vcpkg
          " -replace '\r*\n', ' ') -OutVariable path_to_package_dir
          Invoke-Expression ("
            ./scripts/pack_to_single_file.ps1 
              -DirPath $path_to_package_dir 
              -CompressedFileNameIfRequired ${{ matrix.os }}_${{ matrix.build_type }}.7z
          " -replace '\r*\n', ' ') -OutVariable path_to_package
          $version = "v$((Get-Content -Path './vcpkg.json' -Raw | ConvertFrom-Json).'version-string')"
          
          "path_to_package_dir=$path_to_package_dir" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
          "current_release_version=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

      - name: List Package(s) Info
        id: get_release_info
        if: matrix.os == 'ubuntu-latest' && matrix.build_type == 'Release'
        run: |
          echo "Release Version: ${{ env.current_release_version }}"
          tree -L 3 '${{ env.path_to_package_dir }}'

          echo "release_version=${{ env.current_release_version }}" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: all
          path: ${{ env.path_to_package_dir }}/*

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Verify artifacts and prepare release info
        run: |
          tree -L 3 ./artifacts
          echo "current_release_tag_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "current_release_version=${{ needs.build.outputs.release_version }}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ env.current_release_tag_id }}
          release_name: Release ${{ env.current_release_version }}
          draft: false
          prerelease: false

      - name: Upload artifacts to release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          cd artifacts/all
          for file in *; do
            echo "Uploading $file"
            gh release upload ${{ env.current_release_tag_id }} "$file" --clobber
          done
